// informacje o systemie
#include "main.h"
#define NUMLINES (static_cast<int>(sizeof(sysmetrics) / sizeof(sysmetrics[0])))



struct {
	int iIndex;
	const wchar_t* szLabel;
	const wchar_t* szDesc;
} sysmetrics[] = {
	SM_CXSCREEN,			TEXT("SM_CXSCREEN"),
							TEXT("Szerokoœæ ekranu w pikselach"),
	SM_CYSCREEN,			TEXT("SM_CYSCREEN"),
							TEXT("Wysokoœæ ekranu w pikselach"),
	SM_CXVSCROLL,			TEXT("SM_CXVSCROLL"),
							TEXT("Szerokoœæ przewijania pionowego"),
	SM_CYHSCROLL,			TEXT("SM_CYHSCROLL"),
							TEXT("Wysokoœæ przewijania poziomego"),
	SM_CYCAPTION,			TEXT("SM_CYCAPTION"),
							TEXT("Wysokoœæ paska tytu³u"),
	SM_CXBORDER,			TEXT("SM_CXBORDER"),
							TEXT("Szerokoœæ krawêdzi okna"),
	SM_CYBORDER,			TEXT("SM_CYBORDER"),
							TEXT("Wysokoœæ krawêdzi okna"),
	SM_CXFIXEDFRAME,		TEXT("SM_CXFIXEDFRAME"),
							TEXT("Szerokoœæ ramki okna dialogowego"),
	SM_CYFIXEDFRAME,		TEXT("SM_CYFIXEDFRAME"),
							TEXT("Wysokoœæ ramki okna dialogowego"),
	SM_CYVTHUMB,			TEXT("SM_CYVTHUMB"),
							TEXT("Wysokoœæ przewijania pionowego"),
	SM_CXHTHUMB,			TEXT("SM_CXHTHUMB"),
							TEXT("Szerokoœæ przewijania poziomego"),
	SM_CXICON,				TEXT("SM_CXICON"),
							TEXT("Szerokoœæ ikony"),
	SM_CYICON,				TEXT("SM_CYICON"),
							TEXT("Wysokoœæ ikony"),
	SM_CXCURSOR,			TEXT("SM_CXCURSOR"),
							TEXT("Szerokoœæ kursora"),
	SM_CYCURSOR,			TEXT("SM_CYCURSOR"),
							TEXT("Wysokoœæ kursora"),
	SM_CYMENU,				TEXT("SM_CYMENU"),
							TEXT("Wysokoœæ paska menu"),
	SM_CXFULLSCREEN,		TEXT("SM_CXFULLSCREEN"),
							TEXT("Szerokoœæ pe³nego ekranu"),
	SM_CYFULLSCREEN,		TEXT("SM_CYFULLSCREEN"),
							TEXT("Wysokoœæ pe³nego ekranu"),
	SM_CYKANJIWINDOW,		TEXT("SM_CYKANJIWINDOW"),
							TEXT("Wysokoœæ okna ale Japonia"),
	SM_MOUSEPRESENT,		TEXT("SM_MOUSEPRESENT"),
							TEXT("A myszka jest?"),
	SM_CYVSCROLL,			TEXT("SM_CYVSCROLL"),
							TEXT("Wysokoœæ strza³ki przewijania pionowego"),
	SM_CXHSCROLL,			TEXT("SM_CXHSCROLL"),
							TEXT("Szerokoœæ strza³ki przewijania poziomego"),
	SM_DEBUG,				TEXT("SM_DEBUG"),
							TEXT("Wersja zapoznawcza?"),
	SM_SWAPBUTTON,			TEXT("SM_SWAPBUTTON"),
							TEXT("Wersja dla leworêcznych?"),
	SM_CXMIN,				TEXT("SM_CXMIN"),
							TEXT("Minimalna szerokoœæ okna"),
	SM_CYMIN,				TEXT("SM_CYMIN"),
							TEXT("Minimalna wysokoœæ okna"),
	SM_CXSIZE,				TEXT("SM_CXSIZE"),
							TEXT("Szerokoœæ przycisków Min/Max/X"),
	SM_CYSIZE,				TEXT("SM_CYSIZE"),
							TEXT("Wysokoœæ przycisków Min/Max/X"),
	SM_CXSIZEFRAME,			TEXT("SM_CXSIZEFRAME"),
							TEXT("Szerokoœæ ramki okna"),
	SM_CYSIZEFRAME,			TEXT("SM_CYSIZEFRAME"),
							TEXT("Wysokoœæ ramki okna"),
	SM_CXMINTRACK,			TEXT("SM_CXMINTRACK"),
							TEXT("Szerokoœæ œledzenia okna"),
	SM_CYMINTRACK,			TEXT("SM_CYMINTRACK"),
							TEXT("Wysokoœæ œledzenia okna"),
	SM_CXDOUBLECLK,			TEXT("SM_CXDOUBLECLK"),
							TEXT("Rozrzut dwukliku w poziomie"),
	SM_CYMINTRACK,			TEXT("SM_CYDOUBLECLK"),
							TEXT("Rozrzut dwukliku w pionie"),
	SM_CXICONSPACING,		TEXT("SM_CXICONSPACING"),
							TEXT("Rozstawienie ikon w poziomie"),
	SM_CYICONSPACING,		TEXT("SM_CYICONSPACING"),
							TEXT("Rozstawienie ikon w pionie"),
	SM_MENUDROPALIGNMENT,	TEXT("SM_MENUDROPALIGNMENT"),
							TEXT("Tekst menu z lewej czy prawej?"),
	SM_PENWINDOWS,			TEXT("SM_PENWINDOWS"),
							TEXT("Pióro?"),
	SM_DBCSENABLED,			TEXT("SM_DBCSENABLED"),
							TEXT("Znaki podwójnej szerokoœci?"),
	SM_CMOUSEBUTTONS,		TEXT("SM_CMOUSEBUTTONS"),
							TEXT("Ile mysz ma przycisków?"),
	SM_SECURE,				TEXT("SM_SECURE"),
							TEXT("System bezpieczny?"),
	SM_CXEDGE,				TEXT("SM_CXEDGE"),
							TEXT("Szerokoœæ krawêdzi 3D"),
	SM_CYEDGE,				TEXT("SM_CYEDGE"),
							TEXT("Wysokoœæ krawêdzi 3D"),
	SM_CXMINSPACING,		TEXT("SM_CXMINSPACING"),
							TEXT("Szerokoœæ miêdzy schowanymi oknami??"),
	SM_CYMINSPACING,		TEXT("SM_CYMINSPACING"),
							TEXT("Wysokoœæ miêdzy schowanymi oknami??"),
	SM_CXSMICON,			TEXT("SM_CXICON"),
							TEXT("Szerokoœæ ma³ej ikony"),
	SM_CYSMICON,			TEXT("SM_CYICON"),
							TEXT("Wysokoœæ ma³ej ikony"),
	SM_CYSMCAPTION,			TEXT("SM_CYSMCAPTION"),
							TEXT("Wysokoœæ ma³ego tytu³u"),
	SM_CXSMSIZE,			TEXT("SM_CXSMSIZE"),
							TEXT("Szerokoœæ ma³ych przycisków Min/Max/X"),
	SM_CYSMSIZE,			TEXT("SM_CYSMSIZE"),
							TEXT("Wysokoœæ ma³ych przycisków Min/Max/X"),
	SM_CXMENUSIZE,			TEXT("SM_CXSIZE"),
							TEXT("Szerokoœæ paska menu"),
	SM_CYMENUSIZE,			TEXT("SM_CYSIZE"),
							TEXT("Wysokoœæ paska menu"),
	SM_ARRANGE,				TEXT("SM_ARRANGE"),
							TEXT("Jak u³o¿yæ ma³e okna?"),
	SM_CXMINIMIZED,			TEXT("SM_CXMINIMIZED"),
							TEXT("Szerokoœæ ma³ego okna"),
	SM_CYMINIMIZED,			TEXT("SM_CYMINIMIZED"),
							TEXT("Wysokoœæ ma³ego okna"),
	SM_CXMAXTRACK,			TEXT("SM_CXMAXTRACK"),
							TEXT("Najwiêksza przeci¹galna szerokoœæ"),
	SM_CYMAXTRACK,			TEXT("SM_CYMAXTRACK"),
							TEXT("Najwiêksza przeci¹galna wysokoœæ"),
	SM_CXMAXIMIZED,			TEXT("SM_CXMAXIMIZED"),
							TEXT("Szerokoœæ zmaks. okna"),
	SM_CYMAXIMIZED,			TEXT("SM_CYMAXIMIZED"),
							TEXT("Wysokoœæ zmaks. okna"),
	SM_NETWORK,				TEXT("SM_NETWORK"),
							TEXT("Jest sieæ?"),
	SM_CLEANBOOT,			TEXT("SM_CLEANBOOT"),
							TEXT("Czysty boot?"),
	SM_CXDRAG,				TEXT("SM_CXDRAG"),
							TEXT("Unikaj przeci¹gniêcia o szerokoœci <="),
	SM_CYDRAG,				TEXT("SM_CYDRAG"),
							TEXT("Unikaj przeci¹gniêcia o wyskoœci <="),
	SM_SHOWSOUNDS,			TEXT("SM_SHOWSOUNDS"),
							TEXT("Wizualizowaæ dŸwiêki?"),
	SM_CXMENUCHECK,			TEXT("SM_CXMENUCHECK"),
							TEXT("Szerokoœæ ticka w menu"),
	SM_CYMENUSIZE,			TEXT("SM_CYMENUCHECK"),
							TEXT("Wysokoœæ ticka w menu"),
	SM_SLOWMACHINE,			TEXT("SM_SLOWMACHINE"),
							TEXT("Wolny komputer?"),
	SM_MIDEASTENABLED,		TEXT("SM_MIDEASTENABLED"),
							TEXT("Bliski Wschód?"),
	SM_MOUSEWHEELPRESENT,	TEXT("SM_MOUSEWHEELPRESENT"),
							TEXT("Scroll jest?"),
	SM_XVIRTUALSCREEN,		TEXT("SM_XVIRTUALSCREEN"),
							TEXT("Punkt odniesienia X ekranu wirtualnego"),
	SM_YVIRTUALSCREEN,		TEXT("SM_YVIRTUALSCREEN"),
							TEXT("Punkt odniesienia Y ekranu wirtualnego"),
	SM_CXVIRTUALSCREEN,		TEXT("SM_CXVIRTUALSCREEN"),
							TEXT("Szerokoœæ ekranu wirtualnego"),
	SM_CYVIRTUALSCREEN,		TEXT("SM_CYVIRTUALSCREEN"),
							TEXT("Wysokoœæ ekranu wirtualnego"),
	SM_CMONITORS,			TEXT("SM_CMONITORS"),
							TEXT("Ile jest monitorów?"),
	SM_SAMEDISPLAYFORMAT,	TEXT("SM_SAMEDISPLAYFORMAT"),
							TEXT("Wszystkie ekrany z t¹ sam¹ palet¹ kolorów?")
};